<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>bot.commands_fh</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DSharpPlus" />
      <PackageReference Include="DSharpPlus.Commands" />
      <PackageReference Include="Humanizer.Core" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\application-fh\application-fh.csproj" />
    </ItemGroup>

</Project>
