<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>infra_fh</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Configuration" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
      <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
      <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Http.Polly" />
      <PackageReference Include="Microsoft.Extensions.Options" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\application-fh\application-fh.csproj" />
      <ProjectReference Include="..\domain-fh\domain-fh.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Data\Repositories\" />
      <Folder Include="Mappers\" />
    </ItemGroup>

</Project>
