<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>application_fh</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\domain-fh\domain-fh.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

</Project>
